option(XRAY_AVX  "Compile with /arch:AVX  (AVX1)"  OFF)
option(XRAY_AVX2 "Compile with /arch:AVX2 (AVX2)"  OFF)

# Mutual exclusion: AVX2 supersedes AVX
if(XRAY_AVX2)
  set(XRAY_AVX OFF CACHE BOOL "" FORCE)
endif()

if(XRAY_AVX2)
  message(STATUS "          AVX: AVX2")
  set(XRAY_AVX_SUFFIX ".AVX2" CACHE INTERNAL "")
  if(CMAKE_CXX_COMPILER_ID STREQUAL MSVC)
    add_compile_options(/arch:AVX2)
  elseif(CMAKE_CXX_COMPILER_ID STREQUAL Clang OR CMAKE_CXX_COMPILER_ID STREQUAL GNU)
    add_compile_options(-mavx2)
  endif()
elseif(XRAY_AVX)
  message(STATUS "          AVX: AVX")
  set(XRAY_AVX_SUFFIX ".AVX" CACHE INTERNAL "")
  if(CMAKE_CXX_COMPILER_ID STREQUAL MSVC)
    add_compile_options(/arch:AVX)
  elseif(CMAKE_CXX_COMPILER_ID STREQUAL Clang OR CMAKE_CXX_COMPILER_ID STREQUAL GNU)
    add_compile_options(-mavx)
  endif()
else()
  message(STATUS "          AVX: Off")
  set(XRAY_AVX_SUFFIX "" CACHE INTERNAL "")
endif()
